name: CI

on: workflow_dispatch

jobs:
  build:
    name: Build on ${{ matrix.os }} with GHC ${{ matrix.ghc }} and Cabal ${{ matrix.cabal }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ["9.6"]
        cabal: ["3.10"]
        include:
          - os: ubuntu-latest
            ghc: "9.4"
          - os: ubuntu-latest
            ghc: "9.2"
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal build
