name: CI

on: workflow_dispatch

jobs:
  build:
    name: ${{ matrix.os }}, ghc ${{ matrix.ghc }}, cabal ${{ matrix.cabal }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ["9.2.1"]
        cabal: ["3.6"]
        include:
          - os: ubuntu-latest
            ghc: "9.0.2"
          - os: ubuntu-latest
            ghc: "8.10.7"
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal build
