name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}, ghc ${{ matrix.ghc }}, cabal ${{ matrix.cabal }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ["8.10.4"]
        cabal: ["3.4"]
        include:
          - os: ubuntu-latest
            ghc: "8.8.4"
          - os: ubuntu-latest
            ghc: "8.6.5"
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal build
